# Important pour comprendre avec circle ci: https://circleci.com/developer
version: '2.1'
orbs:
  # https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@2.0.2
  # https://circleci.com/developer/orbs/orb/circleci/docker
  docker: circleci/docker@2.0.3
  # https://circleci.com/developer/orbs/orb/circleci/heroku
  heroku: circleci/heroku@1.2.6

# Remarque: pas le droit au caractère &
jobs:
  lint_tests:
    # image officielle Circle CI CIMG Python Docker
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Linting
          command: flake8
      - run:
          name: Tests (pytest)
          command: pytest
  deploy_heroku:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          name: Configuration des variables
          # Attention DEBUG prend la valeut 'False' et non False
          # Astuce dans settings
          command: |
            heroku config:set DEBUG_COLLECTSTATIC=1 -a $HEROKU_APP_NAME
            heroku config:set SECRET_KEY=$SECRET_KEY -a $HEROKU_APP_NAME
            heroku config:set SENTRY_DSN=$SENTRY_DSN -a $HEROKU_APP_NAME
            heroku config:set DEBUG=False -a $HEROKU_APP_NAME
      - heroku/deploy-via-git

workflows:
  main:
    jobs:
      - lint_tests
      - docker/publish:
          # le format ${VARIABLE,,} met la variable en minuscule
          # obligatoire pour docker
          # plus d'info: https://wiki.bash-hackers.org/syntax/pe
          # Les variables built-in: https://circleci.com/docs/2.0/variables/
          image: ${CIRCLE_PROJECT_USERNAME,,}/p13
          # Remarques:
          # le tag est automatiquement mis avec la valeur $CIRCLE_SHA1
          # Dans les paramètre du projet dans circleci définir les variables:
          #   DOCKER_LOGIN
          #   DOCKER_PASSWORD
          requires:
            - lint_tests
          filters:
            branches:
              only: main
      - deploy_heroku:
          # Penser au Procfile
          requires:
            - docker/publish
          # https://support.circleci.com/hc/en-us/articles/115015953868-Filter-workflows-by-branch-
          filters:
            branches:
              only: main
# Pour voir d'autres manières pour s'authentifier sur docker hub
#       https://circleci.com/docs/2.0/private-images/