#version: 2.1
#orbs:
#  python: circleci/python@1.5.0
#workflows:
#  sample:
#    jobs:
#      - build-and-test
#      - build-and-push-dockerhub:
#          filters:
#            branches:
#              only: master
#          requires:
#            - build-and-test
#      - build-and-push-heroku:
#          filters:
#            branches:
#              only: master
#          requires:
#            - build-and-push-dockerhub
#jobs:
#  build-and-test:
#    docker:
#      - image: cimg/python:3.10.2
#    steps:
#      - checkout
#      - python/install-packages:
#          pkg-manager: pip
#          pip-dependency-file: requirements.txt
#      - run:
#          name: Run tests
#          command: pytest
#  build-and-push-dockerhub:
#    docker:
#      - image: cimg/python:3.10.2
#    steps:
#      - checkout
#      - setup_remote_docker:
#          docker_layer_caching: true
##      - run:
##          name: Build Docker image
##          command: docker build -t docker-oc-lettings:0.1 .
#      - run:
#          name: Login to DockerHub
#          command: docker login --username boukaii --password Qjkayb1993
##      - run:
##          name: Link to DockerHub
##          command: docker tag docker-test_variable:0.1 $test_name/oc-lettings-site:$test_variable
##      - run:
##          name: push Docker image
##          command: docker push $DOCKERHUB_USERNAME/oc-lettings-site:$CIRCLE_SHA1
#      - run:
#          name: Login to DockerHub
#          command: docker build -t test1 .
##      - run:
##          name: Login to DockerHub
##          command: docker tag test1 $DOCKER_LOGIN/$DOCKER_REPO:test1
##                  docker tag local-image:test1 new-repo:test1
#      - run:
#          name: Login to DockerHub
##          command: docker push $test1/$DOCKER_REPO:$CIRCLE_SHA1
##          command: docker push $DOCKER_USER/$DOCKER_REPO:test1
#          command: docker push $DOCKER_LOGIN/test1
##
##DOCKER_LOGIN
##DOCKER_PASSWORD
##
#
#
#
#
#
#
#
#
#
#  build-and-push-heroku:
#    machine: true
#    steps:
#      - checkout
#      - run:
#          name: Setup Heroku
#          command: curl https://cli-assets.heroku.com/install.sh | sh # run a script to set up Heroku
#      - run:
#          name: Build and push Docker image to Heroku
#          command: |
#            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
#            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a $HEROKU_APP_NAME web
#            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a $HEROKU_APP_NAME web
#      - run:
#          name: Migrate database
#          command: |
#            HEROKU_API_KEY=${HEROKU_API_KEY} heroku run python manage.py migrate -a $HEROKU_APP_NAME






























version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  docker: circleci/docker@2.0.1

workflows:
  deploy:
    jobs:
      - build_and_test
      - build_push_docker_hub:
          requires:
            - build_and_test

      - heroku/deploy-via-git:
          requires:
            - build_and_test
            - build_push_docker_hub
          filters:
           branches:
             only: master
          pre-steps:
            - heroku/install
            - run:
                command: |
                  heroku config:set SENTRY_URL=$SENTRY_URL -a oc-lettings-123
                  heroku config:set SECRET_KEY=$SECRET_KEY -a oc-lettings-123
                  heroku config:set DATABASE_URL=$DATABASE_URL -a oc-lettings-123
                  heroku config:set SQLITE_URL=$SQLITE_URL -a oc-lettings-123

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          name: Install Django and dependencies
          command: |
           pip install -r requirements.txt
      - run:
          name: Run tests and linting
          command: |
            pytest
            flake8
  build_push_docker_hub:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/oc-lettings
          extra_build_args: "-t $DOCKER_LOGIN/oc-lettings"
          tag: $CIRCLE_SHA1
      - docker/push:
          image: $DOCKER_LOGIN/oc-lettings
          tag: "latest"
      - docker/push:
          image: $DOCKER_LOGIN/oc-lettings
          tag: $CIRCLE_SHA1