version: 2.1
orbs:
  python: circleci/python@1.5.0
workflows:
  sample:
    jobs:
      - build-and-test:
      - build-and-push-dockerhub:
          filters:
            branches:
              only: master
          requires:
            - build-and-test
      - build-and-push-heroku:
          filters:
            branches:
              only: master
          requires:
            - build-and-push-dockerhub


jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run:
          name: Run tests
          command: pytest
  build-and-push-dockerhub:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: docker build -t docker-oc-lettings:0.1 .
      - run:
          name: Login to DockerHub
          command: docker login --username boukaii --password Qjkayb1993
#          command: docker login --username $DOCKER_LOGIN --password $DOCKER_PASSWORD
      - run:
          name: Link to DockerHub
          command: docker tag docker-oc-lettings:0.1 boukaii/test1:$CIRCLE_SHA1
      - run:
          name: push Docker image
          command: docker push boukaii/test1:$CIRCLE_SHA1




  build-and-push-heroku:
    machine: true
    steps:
      - checkout
      - run:
          name: Setup Heroku
          command: curl https://cli-assets.heroku.com/install.sh | sh # run a script to set up Heroku
      - run:
          name: Build and push Docker image to Heroku
          command: |
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a $HEROKU_APP_NAME web
#            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a $HEROKU_APP_NAME web
      - run:
          name: Migrate database
          command: |
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku run python manage.py migrate -a $HEROKU_APP_NAME